#!/usr/bin/env bash

# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_information() {
    local domain="$1"
    local subdomain="$2"
    local ip

    case "$subdomain" in
        www)
            ip="54.197.43.185"
            ;;
        lb-01)
            ip="54.197.43.185"
            ;;
        web-01)
            ip="34.224.16.215"
            ;;
        web-02)
            ip="54.82.198.143"
            ;;
        *)
            echo "Unknown subdomain: $subdomain"
            return
            ;;
    esac

    echo "The subdomain $subdomain is a A record and points to $ip"
}

if [ "$#" == 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" == 2 ]; then
    domain_information "$1" "$2"
fi

