#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_information () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $NF}')
    echo "The subdomain $2 is a $line record and points to $3"
}

if [ "$#" == 1 ]
then
  domain_information "$1" "www" "54.197.43.185"
  domain_information "$1" "lb-01" "54.197.43.185"
  domain_information "$1" "web-01" "34.224.16.215"
  domain_information "$1" "web-02" "54.82.198.143"
elif [ "$#" == 2 ]
then
  domain_information "$1" "$2"
fi
